### ISSUE TITLE
'nan' loss during training

### ISSUE THREAD

**Issue by roxie62** [brandstetter-johannes/LPSDA#2]
Dear authors, thanks for sharing the code for your excellent work. I have run your code with your suggested step.

However, with the KS experiments, I keep having 'nan' loss in the first few rounds of the training with the default configuration.

Therefore, would you please take a look and help me address the problem? Thanks very much for your help! Looking forward to your reply.

**Comment by brandstetter-johannes** [comment]
Dear @roxie62, thanks for sharing!
I can hardly believe that this is due to the networks or LPSDA. It might however be that you encounter some bad trajectories.
Could you try to generate new training trajectories? 

But please don't delete the old ones, I want to figure out what the problem actually is :)
